DevOps:
  - paths:
      - 'devops*'
      - 'infrastructure/**'
      - 'ci/**'
      - 'docker/**'
      - '**/.github/**'

documentation:
  - paths:
      - 'docs/**'
      - '**/*.md'
      - 'README.md'
      - 'documentation/**'

Server:
  - paths:
      - '**/server/**'

UI:
  - paths:
      - '**/client/**'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.html'

Test:
  - paths:
      - '**/*.test.*'
      - '**/tests/**'
      - '**/__tests__/**'
      - '**/test/**'
