DevOps:
  - path: 'devops*'
  - path: 'infrastructure/**'
  - path: 'ci/**'
  - path: 'docker/**'
  - path: '**/.github/**'

documentation:
  - path: 'docs/**'
  - path: '**/*.md'
  - path: 'README.md'
  - path: 'documentation/**'

Server:
  - path: '**/server/**'

UI:
  - path: '**/client/**'
  - path: '**/*.css'
  - path: '**/*.scss'
  - path: '**/*.html'

Test:
  - path: '**/*.test.*'         # Matches files like *.test.js, *.test.ts, *.test.py etc.
  - path: '**/tests/**'         # Matches any files inside any tests folder at any depth
  - path: '**/__tests__/**'     # Common test folder pattern in many repos
  - path: '**/test/**'          # Matches folders named test (singular)
