name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: 'New Features 🚀'
    labels:
      - enhancement
      - feature
  - title: 'Bug Fixes 🐛'
    labels:
      - bug
      - fix
  - title: 'Documentation 📚'
    labels:
      - documentation
      - docs
exclude-labels:
  - ignore-for-release
  - do-not-merge
