name: Label Pull Requests

on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: '.github/labeler.yml'
          sync-labels: true
