name: Release Drafter

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Release Drafter
        id: drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect and Add New Contributors Section
        id: new_contrib
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const releaseName = (await github.rest.repos.listReleases({owner, repo})).data.find(r => r.draft);
            if (!releaseName) {
              console.log("No draft release found; skipping new contributors detection.");
              return;
            }
            const draftRelease = releaseName;

            // Get all contributors ever
            async function getAllContributors(page = 1, contributors=[]) {
              const response = await github.rest.repos.listContributors({owner, repo, per_page: 100, page});
              contributors.push(...response.data);
              if (response.data.length === 100) {
                return getAllContributors(page+1, contributors);
              }
              return contributors;
            }
            const allContributors = await getAllContributors();

            // Get contributors in this draft release via PRs merged between last release and now
            // Simplified by collecting contributors on commits of the draft release tag (if exists)
            // or all contributors from merged PRs in recent commits -  custom logic may vary

            // For demonstration, assume all contributors on this release are:
            const currentContributors = draftRelease.author ? [draftRelease.author.login] : [];

            // Find new contributors = those in currentContributors but not in allContributors (excluding current release)
            // In practice, you'd collect contributors from commits of current release tag

            // Here, for demonstration, we just add all contributors as new contributors
            const newContributors = currentContributors;

            if (!newContributors.length) {
              console.log("No new contributors detected.");
              return;
            }

            // Create markdown list of new contributors
            const newContribList = newContributors.map(u => `- @${u}`).join('\n');

            // Append "New Contributors" section to the release body
            const updatedBody = draftRelease.body + `\n\n## New Contributors\n${newContribList}`;

            // Update the draft release via GitHub API
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: draftRelease.id,
              body: updatedBody,
              draft: true,
              tag_name: draftRelease.tag_name,
              name: draftRelease.name
            });

            console.log("Draft release updated with new contributors section.");
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
